version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development

  chrome:
    build:
      context: .
      dockerfile: Dockerfile.chrome
    # No ports needed unless you need external access to the browser for debugging

networks:
  default:
    # Default network configuration
